### PR TITLE
Change takeaway UI

### LINKED ISSUE #69: Consider writing out top-level numbers as takeaways
Here's what the summary statistics at the top currently look like:
Screenshot 2021-08-21 09 01 53

This highlights the numbers well, but has a couple drawbacks IMO:
* Net cost is confusing
* Winner/loser share seems a bit awkward (I try to avoid "loser" in general)
* Could understate the connection between the number and its meaning

An alternative could be writing out the takeaways. Here's my shot at this ([Figma](https://www.figma.com/file/GeQiEpTgGUZGzPLiVZN1oA/Summary-statistics?node-id=0%3A1)):

image

Another example:
image

This is still awkward in a couple ways:
* No good way I'm aware of to clearly describe the budgetary impact
* I don't think we should color the inequality change (since it's somewhat partisan), but leaving it gray makes that choice hard to hide

But I think it could be quicker for users to absorb.

### LINKED ISSUE #72: Add waterfall reporting change to net income in individual page
The existing slider-waterfall is useful, but I think the first thing the user sees should mirror the first thing in the population graph: a decomposition of changes. This chart could be hidden if the policy reform doesn't affect them.

This would also make the default slider value issue in #71 less important if that becomes challenging.

### PR DESCRIPTION
**Pull request by nikhilwoodruff**
Fixes #69 

Example:
image

### CODE REVIEW

**Comment by MaxGhenis** [comment]
could you add line breaks so we consistently have:
```
reform produces
x net surplus
```
(no change)
```
poverty
falls x%
```
```
x% of people
come out ahead
```
```
x% of people
come out behind
```

**Comment by nikhilwoodruff** [comment]
@MaxGhenis added those changes.

**Comment by nikhilwoodruff** [comment]
Just added to this:

- Fixes #90 

The waterfall for the household impact page is now on the differences only, by reform to be consistent with the population chart. I also consolidated these two charts a bit in the code (they use the same underlying function).

**Comment by MaxGhenis** [comment]
This introduced a bug when running over the population with no reform. This works in the [live version](https://uk.policyengine.org/population-results) but now produces [this error](https://gist.github.com/MaxGhenis/dd98191692502dc54e2c1a51ebfafb8b).

**Comment by MaxGhenis** [comment]
Looks great though!
image

**Review by MaxGhenis — APPROVED** [review]
approved after the no-reform issue is resolved

**Comment by MaxGhenis** [comment]
Could you actually try putting `Poverty falls x%` back on one line, but have it be vertically centered so it's center-aligned with the other boxes?

**Comment by MaxGhenis** [comment]
Looks like the mobile view needs some work, could this have to do with https://github.com/UBICenter/ubicenter.py/pull/14? The live site looks fine on mobile.
image

**Comment by MaxGhenis** [comment]
This could wait for the beta over the video, but it'd be good to have the final color in the waterfall be dark gray if it's negative. Or maybe even dark green or red to match the headline number...but then should the provisions also have that coloring? Not-blue would be a good start.

Example of UK:
image
and household:
image

**Comment by nikhilwoodruff** [comment]
> Looks like the mobile view needs some work, could this have to do with [UBICenter/ubicenter.py#14](https://github.com/UBICenter/ubicenter.py/pull/14)? The live site looks fine on mobile.

@MaxGhenis just tested, this only happens on my end when I've resized the window without refreshing (resizing -> refetching results avoids this issue). I think this is down to Plotly not auto-adjusting, and since most people aren't going to be resizing their window, seems like it's not too major?

**Comment by nikhilwoodruff** [comment]
> This could wait for the beta over the video, but it'd be good to have the final color in the waterfall be dark gray if it's negative. Or maybe even dark green or red to match the headline number...but then should the provisions also have that coloring? Not-blue would be a good start.

I agree with the not blue, and I think dark gray would work better than green or red

**Comment by nikhilwoodruff** [comment]
New color for dark gray bars:

image

**Comment by nikhilwoodruff** [comment]
OK, bug fixed (it was caused by an empty reform having a final cost but no subcomponents)

**Pull request merged**
